### ISSUE TITLE
影响阅读的两个问题，及一处浏览器兼容性问题

### ISSUE THREAD

**Issue by ShadowPower** [ihewro/typecho-theme-handsome#10]
用了一段时间发现三个比较严重的问题：
1. 链接和普通文本的外观一致，无法区分；
2. 评论不能换行；
3. “时光机”页面中的三个图标不能在Firefox中显示。

希望能在以后的版本中解决 #

**Comment by ihewro** [comment]
git it ~ 下个版本会陆续修复~

**Comment by ihewro** [comment]
测试了一下，结果：
1. 已经发现这个问题了！
2. 会更新哒！
3. 我的可以在Firefox显示呀？

![2017-01-16_180010](https://cloud.githubusercontent.com/assets/20165605/21978453/a598e2f0-dc15-11e6-9af5-23ffcd4f08ad.png)
