### ISSUE TITLE
给音乐播放器提一个小建议

### ISSUE THREAD

**Issue by ShangJixin** [ihewro/typecho-theme-handsome#11]
我觉得把原先qqdie的换成网易云的比较好QwQ，想直接调用网易云的歌单进行播放，还能给服务器减少份存储音乐文件的负担，希望下个版本采纳我的建议

**Comment by ihewro** [comment]
get it ! 我可以尝试下

**Comment by xlsw** [comment]
wordpress就有一个不错的支持网易云音乐的插件。听说typecho就是抽丝剥茧后的wordpress，是不是可以借鉴一下代码，嘿嘿嘿
插件主页https://fatesinger.com/74369

**Comment by ihewro** [comment]
@xlsw 我可以参考一下。
但是最近有点忙
