### ISSUE TITLE
关于html的语言标识

### ISSUE THREAD

**Issue by ShangJixin** [ihewro/typecho-theme-handsome#12]
原主题的是这样的

-----
DOCTYPE HTML html class="no-js"
-----

建议设置成这样的，弄个语言的标识能对Google的收录好点吧QwQ

-----
DOCTYPE HTML html class="no-js" lang="zh-CN"
-----

**Comment by ihewro** [comment]
好，下个版本会加上lang属性(ÒωÓױ)

**Comment by ihewro** [comment]
下个版本会依据此回答：https://www.zhihu.com/question/20797118 进行更改(∩_∩)
