### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by TChenQuan** [ihewro/typecho-theme-handsome#20]
想主题自带的音乐播放器可以选择关闭   不在前台添加代码

其实也是偷懒每次把代码都写到了自定义里面  然后服务器用的脚本自动更新  每次更希望都得自己来删代码
你知道那种自己死都翻不到的心情么

**Comment by ihewro** [comment]
好的。话说自动更新是什么鬼呀？好厉害

**Comment by TChenQuan** [comment]
自动更新是  自己弄得脚本隔12小时 git clone
