### ISSUE TITLE
关于文章编辑器的小建议

### ISSUE THREAD

**Issue by ldnn97** [ihewro/typecho-theme-handsome#22]
用了下Editor.md for Typecho这个插件，发现兼容性还挺好的，就是在表格和代码样式方面有些问题，后期版本可以尝试加入这个插件，这样文章的编辑功能就更强大了。

**Comment by ShangJixin** [comment]
表示我也一直在用QwQ

**Comment by ihewro** [comment]
表格与代码样式有什么问题呢，能否具体说一下呢？
这个是插件和主题没有多大关系吧

**Comment by ldnn97** [comment]
我是个前端小白，也不太清楚问题出在哪里，打开插件里的接管前台Markdown解析之后，代码块的行数显示就会出现问题，表格是没有边框，都不算大问题。
![1](https://cloud.githubusercontent.com/assets/12992623/22380089/0f6679f6-e4f7-11e6-9877-b5ccaed906b4.png)

**Comment by ihewro** [comment]
应该是CSS冲突了，我去测试一下

**Comment by ihewro** [comment]
今天测试了一下，应该是css的冲突，可以把插件设置的：
`接管前台Markdown解析并启用ToC、TeX科学公式、流程图 Flowchart、时序图 Sequence Diagram 等扩展
` 选择`否`
即可
