### ISSUE TITLE
关于表情的bug

### ISSUE THREAD

**Issue by ShangJixin** [ihewro/typecho-theme-handsome#23]
邮件提醒的时候引用的表情地址错误 类似于
https://mail.qq.com/usr/themes/handsome/img/emoticon/8.jpg
导致碎图
另左面侧边栏的导航如果能在后台自定义的话那就方便了

**Comment by ihewro** [comment]
1. 因为引用的是相对路径，相对与本站就是正确的图片地址，相对于邮箱就是错误的地址。除非把OwO.json 里面的图片地址改为绝对地址。（下个版本可能考虑直接用新浪图床，不用本地的图片了，这样也比较稳定）

2. 恩恩，下个版本可能会增加这个设置
