### ISSUE TITLE
移动端代码样式不利于阅读

### ISSUE THREAD

**Issue by ldnn97** [ihewro/typecho-theme-handsome#24]
如果一行代码长了，会自动到下一行，这样程序太难懂了，最好还是一行，有个滑动条横向滑动阅读程序。

**Comment by ihewro** [comment]
你的是最新版本的吗？
现在的版本已经修订了这个问题。详见 issue #16

**Comment by ldnn97** [comment]
我更新到最新的，还是不行。

**Comment by ihewro** [comment]
那把你的博客地址还有使用的浏览器型号发过来吧

**Comment by ldnn97** [comment]
我试了iphone的safari和flyme系统自带的浏览器都不行，地址:ldnn97.cn

**Comment by ihewro** [comment]
可能我用的那段css不兼容这些浏览器，下一个版本更新一下~
