### ISSUE TITLE
时光机如何实现？

### ISSUE THREAD

**Issue by ykla** [ihewro/typecho-theme-handsome#28]
`

> 时光机: 填写地址的时候，必须填写为 cross.html 。内容框里面不用填任何东西，这个页面在前台就可以发布“说说”，用来记录你的日常和心情的~ 关于删除说说：在后台的评论管理中删掉该页面的对应评论即可。

`

请问新建地址是网站根目录还是什么目录？如果不是，我新建了，那么在前台如何发布说说？

**Comment by ihewro** [comment]
新建独立页面。后台的新建里面有该选项呀？

**Comment by ykla** [comment]
/index.php/cross.html新建后，并没有发现什么啊？

**Comment by ldnn97** [comment]
1. 创建独立页面
2. 设置如图
![1](https://cloud.githubusercontent.com/assets/12992623/22550688/2cf70136-e98c-11e6-9bdd-562f4a1ec5b7.png)

**Comment by ykla** [comment]
@ldnn97 你的网站看起来开始了伪静态。我没有开启，建立是/index.php/cross.html。建立后并没有发现何处可以发什么东西…

**Comment by ldnn97** [comment]
@ykla 我关掉伪静态后没有问题呀，在页面里的时光机，前提是你的评论功能没问题，也就是把检查url和垃圾评论的开关关掉。

**Comment by ykla** [comment]
@ldnn97 感谢你了，明天彻底看下。我是nginx

**Comment by ykla** [comment]
@ldnn97  问题依旧，修复了评论问题。我的网站hmxs.tk

**Comment by ldnn97** [comment]
@ykla 现在的问题是在时光机页面发说说显示不出来吗？

**Comment by ykla** [comment]
完成

**Comment by ykla** [comment]
@ldnn97谢谢你！
