### ISSUE TITLE
无法评论

### ISSUE THREAD

**Issue by ykla** [ihewro/typecho-theme-handsome#29]
无法评论。不知道怎么回事。其他主题可以评论。

**Comment by ihewro** [comment]
查看帮助文档的评论系统部分。如果还不行，再启用伪静态设置尝试一下

**Comment by ykla** [comment]
好的，我明天搞下伪静态看看

**Comment by ldnn97** [comment]
设置-评论 关掉 **检查评论来源页 URL 是否与文章链接一致**  和 **开启反垃圾保护**
