### ISSUE TITLE
没错 又是我  我来了

### ISSUE THREAD

**Issue by TChenQuan** [ihewro/typecho-theme-handsome#3]
https://www.illn.in/rolan-ruan-jian-tui-jian.html
https://www.illn.in/gravatar-x-typecho.html
有CDN  看看这两个页面

区别有点大。。。
![qq 20161223183632](https://cloud.githubusercontent.com/assets/15852697/21452004/cc482788-c93e-11e6-8e06-db8b17bcaa05.png)
![qq 20161223183647](https://cloud.githubusercontent.com/assets/15852697/21452005/cc4a16ce-c93e-11e6-8a3c-6c6f725dd53f.png)

**Comment by TChenQuan** [comment]
顺便问一句你邮件插件用的什么发送方式

**Comment by TChenQuan** [comment]
找到原因了
`<b>XXXX<b>`

**Comment by ihewro** [comment]
邮件通知我用的第一个smtp 方式，不过很可能是主机问题，发信不了了（之前是正常的）~

**Comment by ihewro** [comment]
另：评论邮件插件选用一个好用的邮箱很重要啊~我今天换成阿里云的企业邮箱，可以了！

**Comment by TChenQuan** [comment]
我用网易的可以  阿里云 企业的则不行  和你相反0.0

**Comment by TChenQuan** [comment]
侧边栏的组成在后台弄个添加自定义代码吧
每次都得改文件0.0有点麻烦的说0.0  评论添加表情这个功能
https://github.com/coocy/emoji
http://coocy.github.io/emoji/

自己先实现下

文字表情

**Comment by TChenQuan** [comment]
https://github.com/DIYgod/OwO

**Comment by ihewro** [comment]
表情之前确实想添加来着，后来和instantclick有点冲突，还要自己修改css，就搁置了~~争取最近加上！

**Comment by ihewro** [comment]
侧边栏的组成 在后台加个设置代码的框，要是用户对html这些不熟悉，太不友好了吧

**Comment by TChenQuan** [comment]
标签用这个https://github.com/DIYgod/OwO  配置的json使用php生成就可以了这样用户就可以在后台添加表情

**Comment by TChenQuan** [comment]
邮件评论又开始有毒了
后台2.0测试可以发布
然呢让前台怎么评论都不发邮件

**Comment by TChenQuan** [comment]
你阿里云企业邮箱怎么填写的配置信息？

**Comment by TChenQuan** [comment]
`邮件发送失败：SMTP connect() failed.`

**Comment by ihewro** [comment]
我用163之前也这样，后台可以，前台也不行，就换了阿里云企业邮箱

smtp地址填写：`smtp.mxhichina.com`
其他不变。
ps:线上环境总是有毒~~~本地都行，线上一堆问题，哭哭哭

**Comment by TChenQuan** [comment]
+1

**Comment by TChenQuan** [comment]
我还去买了个域名为了评论回复

**Comment by ihewro** [comment]
我可以给你分配账户啊[滑稽]~

**Comment by TChenQuan** [comment]
`notice.wiki` 才买的热乎着呢

**Comment by ihewro** [comment]
你的博客我没办法评论哎？ @TChenQuan

**Comment by ihewro** [comment]
你第一个问题：页面错乱 是什么原因呀？我的有一个页面也错乱了~奇怪~

**Comment by ihewro** [comment]
找到问题了~评论区有`<div>`标签导致整个页面的div标签闭合错误~cry
