### ISSUE TITLE
移动端上chrome浏览器无法自动播放音乐

### ISSUE THREAD

**Issue by ykla** [ihewro/typecho-theme-handsome#30]
Chrome  55。 QQ浏览器支持。当音乐插件隐藏时。

**Comment by ihewro** [comment]
隐藏了代表不启用该插件，自然无法播放音乐了

**Comment by ykla** [comment]
电脑页面隐藏时音乐仍会播放

**Comment by ykla** [comment]
QQ浏览器支持，都在隐藏下…

**Comment by ldnn97** [comment]
设置外观里有音乐播放器的开关。

**Comment by ykla** [comment]
-在隐藏状态下，手机QQ浏览器和电脑端的chrome/IE11可以正常播放。手机chrome无法播放。
-在开启状态下手机QQ浏览器和电脑端可以正常播放。手机chrome可以播放。

**Comment by ihewro** [comment]
这可能是一个bug。找个时间看一下
现在暂时的解决办法是：如果想自动播放的话，手机端就别隐藏了。

**Comment by ihewro** [comment]
测试结果：隐藏播放器后，下面关于播放器的设置项目都会失效，这是符合预期的设计的。

**Comment by ihewro** [comment]
如果有问题的话，可以继续反馈哦~先给关了
