### ISSUE TITLE
无法评论

### ISSUE THREAD

**Issue by beyondskyway** [ihewro/typecho-theme-handsome#31]
对了，启用主题后无法评论了，开启了伪静态选项的, 地址：http://121.42.205.71/
（PS：你的blog点击跳转有问题，应该是https的问题，非https下可正常访问。所以无法在那边评论求助）

撤回主题1.6也是一样的，只有时光机可以，留言板和文章都无法评论

**Comment by ihewro** [comment]
博客地址是ihewro.com  ihewro.xyz不再使用了！

有**取消选中**
`设置——评论——检查评论来源页 URL 是否与文章链接一致/ 开启反垃圾保护`
这两项了吗？

#29 也提到了这个问题

**Comment by ihewro** [comment]
还有建议升级到最新版本2.0.X，修复若干bug

**Comment by beyondskyway** [comment]
👍
