### ISSUE TITLE
知道为什么网站SEO效果差了

### ISSUE THREAD

**Issue by ShangJixin** [ihewro/typecho-theme-handsome#32]
觉得在主题代码上，应该先加载文章，然后再加载两个侧栏，最后加载footer 先加载文章的话觉得真的有利于seo

**Comment by ihewro** [comment]
可能和这个关系不大吧。代码加载肯定是按照dom顺序加载的。在我观念中，不可能先加载文章的吧，因为DOM的顺序是：左侧边栏——中间部分（文章）——右侧边栏。

typecho其他的主题如果有左侧边栏的话，也是先加载左侧边栏的。
