### ISSUE TITLE
友情链接插件bug

### ISSUE THREAD

**Issue by ykla** [ihewro/typecho-theme-handsome#34]
数据表建立失败，友情链接插件启用失败。错误号：42S01

**Comment by ihewro** [comment]
你使用的主机的PHP环境是什么样子的呢?

这个应该是插件本身的问题,不支持你的数据库?

如果无法解决,可以不启用这个插件(不会影响其他功能),首页的友情链接只能自己手动修改了

**Comment by ykla** [comment]
PHP7 这个插件其他人也有报错。

**Comment by xlsw** [comment]
这个错误代码的意思是已存在该表，你只需要进数据库删除这个插件的数据表（一般为typecho_links）即可！
