### ISSUE TITLE
一处改进

### ISSUE THREAD

**Issue by chakhsu** [ihewro/typecho-theme-handsome#35]
建议将comments.php中的js放到footer.php里，因为js是解析器阻塞性资源，页面渲染的时候可能会导致重绘什么的乱七八糟影响，从而影响前端性能。

**Comment by ihewro** [comment]
谢谢建议哈。
有些js由于为了兼容instantclick被迫在不放在全局的位置(所以放在comments.php里了)，还有一些是控制css样式表加载的，放在最后，整个网页会闪一下。

有时间改进一下这些js加载顺序

**Comment by ihewro** [comment]
看了你的代码才知道可以用
```
<?php if($this->allow('comment')): ?>
```
然后把代码放在footer就可以了，(*^__^*)
