### ISSUE TITLE
TOC JS错误

### ISSUE THREAD

**Issue by snailium** [ihewro/typecho-theme-handsome#36]
测试了IE 11和Chrome 56，均报错。

IE 11的控制台错误：

SCRIPT438: 对象不支持“tocify”属性或方法
toc.min.js (12,3)

Chrome 56的控制台错误：

Uncaught TypeError: $(...).tocify is not a function
    at HTMLDocument.<anonymous> (toc.min.js:12)
    at j (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at Function.ready (jquery.min.js:2)
    at HTMLDocument.I (jquery.min.js:2)

目前handsome使用的是master(291bc17)

**Comment by ihewro** [comment]
有测试页面吗？

我这边是没有报错的

**Comment by ihewro** [comment]
看这个错误应该是jquery冲突。

很大的可能是使用的插件输出的jquery 与主题本身的输入的jquery冲突的。

可以试试排除一下后台的插件

**Comment by snailium** [comment]
报错页面：https://www.snailium.com/2016/10/24/migrated-from-wordpress-to-typecho
（实际上整个网站都在报错）

查了一下有一个at插件用了1.9.1版本的jquery

但是在Chrome里面trace的结果是调用了2.4.1版本的jquery

**Comment by snailium** [comment]
果然把at插件禁用了就好了

at插件本身有一个不加载jquery功能，但是好像无论怎么设置都会加载

**Comment by ihewro** [comment]
应该是插件本身的问题，你可以直接修改插件，搜索`jquery` ,把输出jquery的代码删掉就没问题了

那就关了issue了哦
