### ISSUE TITLE
无法获取已有评论数

### ISSUE THREAD

**Issue by ming88208** [ihewro/typecho-theme-handsome#37]
换模板之后只有新评论才计数，以前的页面底下和首页都是 暂无评论

**Comment by ming88208** [comment]
博客地址是http://3828.net

**Comment by ihewro** [comment]
我的博客之前也不是使用这个主题的，切换后没有问题。

晚上回去我再测试一下吧

**Comment by ihewro** [comment]
主题的评论数字是调用  数据库的`typecho_contents`表中的`commentsNum`字段的数据。
具体代码是：
```php
<?php $this->commentsNum(_t(' 暂无评论'), _t(' 1 条评论'), _t(' %d 条评论')); ?>
```
应该是你的数据库的数据有问题，你是不是之前迁移到typecho呢，或者对数据库进行了误操作呢？

**Comment by ming88208** [comment]
之前的数据是从多说导入的，用的是多说实时同步插件

**Comment by ihewro** [comment]
在同步的过程中，没有正确的把总评论数目同步过来。

你可以尝试手动再同步几次，或者找插件作者询问一下
