### ISSUE TITLE
正文图片尺寸不对

### ISSUE THREAD

**Issue by ming88208** [ihewro/typecho-theme-handsome#41]
上传的图片如果设定了px值，不能保持原来的横纵比，在电脑上看和手机上看都不正常，希望自适应时只改变大小，不改变比例。不知道是什么问题。附问题链接：http://www.3828.net/comic/Hetalia.html

**Comment by ihewro** [comment]
我这边测试没有图片比例是正确的，见测试页面：https://www.ihewro.com/archives/653/

应该是你的使用什么什么插件？或者自定义js代码。

我看你的页面，每个图片，自动加上了一个宽和高的尺寸，应该是插件的原因吧。

![2017-04-03_092313](https://cloud.githubusercontent.com/assets/20165605/24592829/4aa51b40-184f-11e7-9f5f-f71e922c7e4d.png)


你用的是什么编辑器呢，可能是编辑器的前台解析导致的，也有可能是其他的插件的js代码导致的

**Comment by ming88208** [comment]
把html代码里有关尺寸的部分全部删掉，成功解决，真神奇

**Comment by ming88208** [comment]
我用的是ueditor，不知道有没有更好的编辑器推荐呢

**Comment by ihewro** [comment]
我挺喜欢官方的编辑器的，支持markdown就行。

typecho编辑器还有两种比较好用的：

Markdown 编辑器 Editor.md for Typecho ，主要是支持markdown语法的：https://github.com/DT27/EditorMD

UEditor-for-Typecho，这款是html编辑器，适合新手用，简单方便，功能强大。https://github.com/chanshengzhi/UEditor-for-Typecho

**Comment by xlsw** [comment]
可以试试Ckeditor4Typecho
