### ISSUE TITLE
文章目录无法显示

### ISSUE THREAD

**Issue by FENG-MASTER** [ihewro/typecho-theme-handsome#43]
用md写的,开始是显示文章目录的,后来不知道什么原因,只有"文章目录"标题,而没有目录了,
原因可能是我修改过sidebar.php,但我后来恢复到原来的sidebar.php,似乎还是不行,请问我应该去检查下哪里问题,急

**Comment by FENG-MASTER** [comment]
网站是http://112.74.125.7,还在备案,所以没域名

**Comment by FENG-MASTER** [comment]
似乎是因为我把头图功能关了再开启的缘故

**Comment by FENG-MASTER** [comment]
不知道为什么,就好了

**Comment by FENG-MASTER** [comment]
还是会出现这个问题,希望能得到解决

**Comment by FENG-MASTER** [comment]
http://112.74.125.7/index.php/archives/16/ 详细问题可以直接看我博客的文章

**Comment by ihewro** [comment]
本地测试没有发现问题

测试截屏：
![20170409163529](https://cloud.githubusercontent.com/assets/20165605/24835973/a1c087c2-1cd5-11e7-97a2-051391e332f1.png)


后台装了什么插件吗？

把插件目录截个图吧

**Comment by ihewro** [comment]
自行可以排查一下是不是哪个插件的JS冲突了？

**Comment by FENG-MASTER** [comment]
好,我有空排插下,主要是这个问题是随机出现的,我刚刚也是好的,没有问题,先暂时关闭这个Issue 吧

**Comment by FENG-MASTER** [comment]
顺便说个bug,关于时光机的,第一条说说是无法发送的,起码我这边是,我这边TE 版本 1.0 (14.10.10) ,只有你先点发个图,然后才发了一个说说出去,而且图片无法显示,这之后发说说就是可以的.,

**Comment by ihewro** [comment]
有把后台的`设置->评论->开启反垃圾评论`关闭了吗？
https://handsome.ihewro.com/#/comment

**Comment by FENG-MASTER** [comment]
这个没关,刚刚去关了,谢啦

**Comment by FENG-MASTER** [comment]
找到问题所在了,文章目录显示并不支持所有MD语法,### 标题###,这种格式标题并不支持,会直接导致不显示所有文章内标题
