### ISSUE TITLE
时光机页面 伪静态页面错误

### ISSUE THREAD

**Issue by fanzheng** [ihewro/typecho-theme-handsome#44]
typecho 伪静态页面配置的是 /{slug}

页面为 http://miao.li/cross

但是首页的头像一直有.html 
所以一直点头像进时光机页面一直有错误。

**Comment by ihewro** [comment]
啊，我只考虑了配置如下的用户
```
/{slug}.html
```

不妨自己修改一下`aside.php`。

搜索`cross.html`改成`cross`

之后看有木有办法跟随后台配置，自动匹配这部分内容

**Comment by fanzheng** [comment]
改了之后链接OK了。
