### ISSUE TITLE
时光机在窄屏幕分辨率下排版错误

### ISSUE THREAD

**Issue by KaedeShinoda** [ihewro/typecho-theme-handsome#46]
在设备iPhone5屏幕显示，时光机页面排版有误，望修复。
图见https://i4.buimg.com/1949/7f61c180241d3cd0.png
（这边GitHub不知道为啥上传不了图片……）

**Comment by ihewro** [comment]
错位是因为你的手机分辨率太小了，右边的时间的格式太长了

下次更新的时候，把右边的格式变得短一点吧
