### ISSUE TITLE
适配Aplayer插件问题

### ISSUE THREAD

**Issue by caiyy** [ihewro/typecho-theme-handsome#5]
我的博客里面有用到音乐播放的插件,是每个文章里面的.
然后吧.点进去文章会自动播放相关的音乐.
现在的情况是,进入其他的页面,它还在播放之前进入的文章的音乐...
这个.希望有个开关控制可以解决...

blog:https://www.caiyy.vip/
qq:534450568

**Comment by ihewro** [comment]
这个我知道。你用的应该是apayer吧。这个是由于instantcIick导致的。下个版本尝试修复这个问题

**Comment by caiyy** [comment]
嗯对,就是这个插件.

**Comment by caiyy** [comment]
还有就是,首页的图片应该限制一下比例显示..不然方形图片跟圆形图片太大了~~
比如只显示图片中间的部分,上下不显示

**Comment by ihewro** [comment]
方法：
1.  使用 [FaithPatrick/APlayer-Typecho-Plugin](https://github.com/FaithPatrick/APlayer-Typecho-Plugin) 版本的插件。
2. 在footer.php 增加这两段代码即可。(具体见图示)

```javascript
if (!window.audios) {
    audios = [];
    for (var i = 0; i < APlayers.length; i++) {
        audios[i] = APlayers[i].audio;
    }
}
InstantClick.on('change', function(isInitialLoad) {
  for (var i = 0; i < APlayers.length; i++) {
        audios.push(APlayers[i].audio);
  }
  for(var i = 0; i < audios.length; i++) {if(audios[i]){audios[i].pause()}};
```

![2017-02-06_140625](https://cloud.githubusercontent.com/assets/20165605/22636419/de8d2434-ec75-11e6-8f58-2b34f826cb6c.png)

**Comment by ihewro** [comment]
在最新版2.1.1及其以上版本，在后台的外观设置中：
1. 在`自定义js`中添加
```javascript
if (!window.audios) {
    audios = [];
    for (var i = 0; i < APlayers.length; i++) {
        audios[i] = APlayers[i].audio;
    }
```

2. 在`instantclick回调函数`添加
```javascript
  for (var i = 0; i < APlayers.length; i++) {
        audios.push(APlayers[i].audio);
  }
  for(var i = 0; i < audios.length; i++) {if(audios[i]){audios[i].pause()}};
```
