### ISSUE TITLE
Cross 多用户

### ISSUE THREAD

**Issue by TChenQuan** [ihewro/typecho-theme-handsome#8]
当typecho开启多用户的时候
https://www.illn.in/cross.html
cross 的动态 只要是注册用户都可以发布了。。。

**Comment by ihewro** [comment]
对啊，模板设置的就是只要登录用户就可以发布说说的。

**Comment by ihewro** [comment]
不知道你想怎么改？有啥想法吗？

**Comment by TChenQuan** [comment]
每个用户 都有一个cross?
发现多有户这个功能只能被隐藏或者修改可以支持多用户

**Comment by TChenQuan** [comment]
让cross支持多用户 每个用户都有自己的页面

**Comment by ihewro** [comment]
目前没想出好方法来，可以借鉴一下这个站点的方法：https://smallk.net/
再新建一个cross.php ，这样做法只适合多用户少的站点。
