### ISSUE TITLE
2.0.0即将更新内容

### ISSUE THREAD

**Issue by ihewro** [ihewro/typecho-theme-handsome#9]
1. 后台设置[instantclick回调函数]的一个bug
2. 底部css微调
3. 增加返回底部
4. 增加表情功能
5. 搜索同样支持无刷新
6. 增加返回顶部
7. 图片惰性加载
8. 增加博主标识
9. 引入tooltip.js
10. 针对手机端的侧边栏打开和关闭动画优化处理
11. 前台登录后跳转当前地址（而非首页）

**Comment by TChenQuan** [comment]
再提示你一下  `Header.php` 在后台的外观设置中 加一个  自定义关键词和自定义描述  我上次更新忘了改`header` Google都是 `app, web app, responsive, responsive layout, admin, admin panel, admin dashboard, flat, flat ui, ui kit, AngularJS, ui route, charts, widgets, components. ` 

还有像百度站长中   [Google webmasters](https://www.google.com/webmasters/verification/home?hl=zh-CN) 中需要在header中添加meta标签  重新更新主题 忘了改都没了

可以在后台新增   header自定义代码

**Comment by ihewro** [comment]
get it(๑`灬´๑)

**Comment by TChenQuan** [comment]
美化下video标签？

**Comment by TChenQuan** [comment]
盒子模型 打开首页会闪   第一次打开页面都会闪一下

**Comment by TChenQuan** [comment]
更多的CSS动画

右上角登录
左边隐藏头像和折叠时候


搜索结果预览？

**Comment by TChenQuan** [comment]
给主题写自带的音乐视频播放器吧    后台文章编辑中并不支持html代码

**Comment by ihewro** [comment]
嗯，后面几个版本会好好考虑的，还有技术上的原因的...

**Comment by TChenQuan** [comment]
首页无缝加载文章 在输出 固定的条数在分页
